// Periodic Table Element Data
const elements = [
  {
    atomicNumber: 1,
    symbol: "H",
    name: "Hydrogen",
    atomicWeight: 1.008,
    category: "nonmetal",
    electronConfiguration: "1s¹",
    electronegativity: 2.2,
    density: 0.0000899,
    meltingPoint: -259.14,
    boilingPoint: -252.87,
    discoveryYear: 1766,
    description: "Hydrogen is the lightest element and the most abundant chemical substance in the universe, constituting roughly 75% of all normal matter."
  },
  {
    atomicNumber: 2,
    symbol: "He",
    name: "Helium",
    atomicWeight: 4.0026,
    category: "noble-gas",
    electronConfiguration: "1s²",
    electronegativity: null,
    density: 0.0001785,
    meltingPoint: -272.2,
    boilingPoint: -268.93,
    discoveryYear: 1868,
    description: "Helium is a colorless, odorless, tasteless, non-toxic, inert, monatomic gas, the first in the noble gas group in the periodic table."
  },
  {
    atomicNumber: 3,
    symbol: "Li",
    name: "Lithium",
    atomicWeight: 6.94,
    category: "alkali-metal",
    electronConfiguration: "1s² 2s¹",
    electronegativity: 0.98,
    density: 0.534,
    meltingPoint: 180.54,
    boilingPoint: 1342,
    discoveryYear: 1817,
    description: "Lithium is a soft, silvery-white alkali metal. Under standard conditions, it is the lightest metal and the lightest solid element."
  },
  {
    atomicNumber: 4,
    symbol: "Be",
    name: "Beryllium",
    atomicWeight: 9.0122,
    category: "alkaline-earth-metal",
    electronConfiguration: "1s² 2s²",
    electronegativity: 1.57,
    density: 1.85,
    meltingPoint: 1287,
    boilingPoint: 2470,
    discoveryYear: 1797,
    description: "Beryllium is a relatively rare element in the universe. It is a divalent element which occurs naturally only in combination with other elements in minerals."
  },
  {
    atomicNumber: 5,
    symbol: "B",
    name: "Boron",
    atomicWeight: 10.81,
    category: "metalloid",
    electronConfiguration: "1s² 2s² 2p¹",
    electronegativity: 2.04,
    density: 2.34,
    meltingPoint: 2076,
    boilingPoint: 3927,
    discoveryYear: 1808,
    description: "Boron is a chemical element with symbol B and atomic number 5. Produced entirely by cosmic ray spallation and supernovae and not by stellar nucleosynthesis, it is a low-abundance element in the Solar system and in the Earth's crust."
  },
  {
    atomicNumber: 6,
    symbol: "C",
    name: "Carbon",
    atomicWeight: 12.011,
    category: "nonmetal",
    electronConfiguration: "1s² 2s² 2p²",
    electronegativity: 2.55,
    density: 2.267,
    meltingPoint: 3550,
    boilingPoint: 4027,
    discoveryYear: "Ancient",
    description: "Carbon is a chemical element with symbol C and atomic number 6. It is nonmetallic and tetravalent—making four electrons available to form covalent chemical bonds. It belongs to group 14 of the periodic table."
  },
  {
    atomicNumber: 7,
    symbol: "N",
    name: "Nitrogen",
    atomicWeight: 14.007,
    category: "nonmetal",
    electronConfiguration: "1s² 2s² 2p³",
    electronegativity: 3.04,
    density: 0.0012506,
    meltingPoint: -210.1,
    boilingPoint: -195.79,
    discoveryYear: 1772,
    description: "Nitrogen is a chemical element with symbol N and atomic number 7. It was first discovered and isolated by Scottish physician Daniel Rutherford in 1772."
  },
  {
    atomicNumber: 8,
    symbol: "O",
    name: "Oxygen",
    atomicWeight: 15.999,
    category: "nonmetal",
    electronConfiguration: "1s² 2s² 2p⁴",
    electronegativity: 3.44,
    density: 0.001429,
    meltingPoint: -218.79,
    boilingPoint: -182.95,
    discoveryYear: 1774,
    description: "Oxygen is a chemical element with symbol O and atomic number 8. It is a member of the chalcogen group on the periodic table, a highly reactive nonmetal, and an oxidizing agent that readily forms oxides with most elements as well as with other compounds."
  },
  {
    atomicNumber: 9,
    symbol: "F",
    name: "Fluorine",
    atomicWeight: 18.998,
    category: "nonmetal",
    electronConfiguration: "1s² 2s² 2p⁵",
    electronegativity: 3.98,
    density: 0.001696,
    meltingPoint: -219.67,
    boilingPoint: -188.11,
    discoveryYear: 1886,
    description: "Fluorine is a chemical element with symbol F and atomic number 9. It is the lightest halogen and exists as a highly toxic pale yellow diatomic gas at standard conditions."
  },
  {
    atomicNumber: 10,
    symbol: "Ne",
    name: "Neon",
    atomicWeight: 20.180,
    category: "noble-gas",
    electronConfiguration: "1s² 2s² 2p⁶",
    electronegativity: null,
    density: 0.0008999,
    meltingPoint: -248.59,
    boilingPoint: -246.08,
    discoveryYear: 1898,
    description: "Neon is a chemical element with symbol Ne and atomic number 10. It is a noble gas. Neon is a colorless, odorless, inert monatomic gas under standard conditions, with about two-thirds the density of air."
  },
  {
    atomicNumber: 11,
    symbol: "Na",
    name: "Sodium",
    atomicWeight: 22.990,
    category: "alkali-metal",
    electronConfiguration: "1s² 2s² 2p⁶ 3s¹",
    electronegativity: 0.93,
    density: 0.97,
    meltingPoint: 97.72,
    boilingPoint: 883,
    discoveryYear: 1807,
    description: "Sodium is a chemical element with symbol Na and atomic number 11. It is a soft, silvery-white, highly reactive metal."
  },
  {
    atomicNumber: 12,
    symbol: "Mg",
    name: "Magnesium",
    atomicWeight: 24.305,
    category: "alkaline-earth-metal",
    electronConfiguration: "1s² 2s² 2p⁶ 3s²",
    electronegativity: 1.31,
    density: 1.74,
    meltingPoint: 650,
    boilingPoint: 1090,
    discoveryYear: 1808,
    description: "Magnesium is a chemical element with symbol Mg and atomic number 12. It is a shiny gray solid which bears a close physical resemblance to the other five elements in the second column of the periodic table."
  },
  {
    atomicNumber: 13,
    symbol: "Al",
    name: "Aluminum",
    atomicWeight: 26.982,
    category: "post-transition-metal",
    electronConfiguration: "1s² 2s² 2p⁶ 3s² 3p¹",
    electronegativity: 1.61,
    density: 2.7,
    meltingPoint: 660.32,
    boilingPoint: 2519,
    discoveryYear: 1825,
    description: "Aluminum is a chemical element with symbol Al and atomic number 13. It is a silvery-white, soft, nonmagnetic, ductile metal in the boron group."
  },
  {
    atomicNumber: 14,
    symbol: "Si",
    name: "Silicon",
    atomicWeight: 28.085,
    category: "metalloid",
    electronConfiguration: "1s² 2s² 2p⁶ 3s² 3p²",
    electronegativity: 1.90,
    density: 2.33,
    meltingPoint: 1414,
    boilingPoint: 3265,
    discoveryYear: 1824,
    description: "Silicon is a metalloid with symbol Si and atomic number 14. It is a hard, brittle crystalline solid with a blue-grey metallic luster and is a crucial component in semiconductors."
  },
  {
    atomicNumber: 15,
    symbol: "P",
    name: "Phosphorus",
    atomicWeight: 30.974,
    category: "nonmetal",
    electronConfiguration: "1s² 2s² 2p⁶ 3s² 3p³",
    electronegativity: 2.19,
    density: 1.82,
    meltingPoint: 44.15,
    boilingPoint: 280.5,
    discoveryYear: 1669,
    description: "Phosphorus is a reactive nonmetal with symbol P and atomic number 15. It exists in several forms, including white, red, and black phosphorus, and is essential for life, especially in DNA and ATP."
  },
  {
    atomicNumber: 16,
    symbol: "S",
    name: "Sulfur",
    atomicWeight: 32.06,
    category: "nonmetal",
    electronConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁴",
    electronegativity: 2.58,
    density: 2.07,
    meltingPoint: 115.21,
    boilingPoint: 444.6,
    discoveryYear: "Ancient",
    description: "Sulfur is a nonmetallic element with symbol S and atomic number 16. Known since antiquity, it is bright yellow and commonly found in volcanic regions and hot springs."
  },
  {
    atomicNumber: 17,
    symbol: "Cl",
    name: "Chlorine",
    atomicWeight: 35.45,
    category: "halogen",
    electronConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁵",
    electronegativity: 3.16,
    density: 3.21,
    meltingPoint: -101.5,
    boilingPoint: -34.04,
    discoveryYear: 1774,
    description: "Chlorine is a halogen with symbol Cl and atomic number 17. It is a yellow-green gas at room temperature and is widely used in disinfectants and the production of PVC."
  },
  {
    atomicNumber: 18,
    symbol: "Ar",
    name: "Argon",
    atomicWeight: 39.948,
    category: "noble-gas",
    electronConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶",
    electronegativity: null,
    density: 0.0017837,
    meltingPoint: -189.35,
    boilingPoint: -185.85,
    discoveryYear: 1894,
    description: "Argon is a chemical element with symbol Ar and atomic number 18. It is in group 18 of the periodic table and is a noble gas."
  },
  {
    atomicNumber: 19,
    symbol: "K",
    name: "Potassium",
    atomicWeight: 39.098,
    category: "alkali-metal",
    electronConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s¹",
    electronegativity: 0.82,
    density: 0.89,
    meltingPoint: 63.38,
    boilingPoint: 759,
    discoveryYear: 1807,
    description: "Potassium is a chemical element with symbol K and atomic number 19. It was first isolated from potash, the ashes of plants, from which its name derives."
  },
  {
    atomicNumber: 20,
    symbol: "Ca",
    name: "Calcium",
    atomicWeight: 40.078,
    category: "alkaline-earth-metal",
    electronConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s²",
    electronegativity: 1.00,
    density: 1.55,
    meltingPoint: 842,
    boilingPoint: 1484,
    discoveryYear: 1808,
    description: "Calcium is a chemical element with symbol Ca and atomic number 20. As an alkaline earth metal, calcium is a reactive metal that forms a dark oxide-nitride layer when exposed to air."
  },
  {
    atomicNumber: 21,
    symbol: "Sc",
    name: "Scandium",
    atomicWeight: 44.955,
    category: "transition-metal",
    electronConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹ 4s²",
    electronegativity: 1.36,
    density: 2.985,
    meltingPoint: 1541,
    boilingPoint: 2836,
    discoveryYear: 1879,
    description: "Scandium is a silvery-white transition metal with atomic number 21. Though relatively rare, it is used in aerospace components and sports equipment due to its strength and lightness."
  },
  {
    atomicNumber: 22,
    symbol: "Ti",
    name: "Titanium",
    atomicWeight: 47.867,
    category: "transition-metal",
    electronConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d² 4s²",
    electronegativity: 1.54,
    density: 4.506,
    meltingPoint: 1668,
    boilingPoint: 3287,
    discoveryYear: 1791,
    description: "Titanium, symbol Ti, is a lustrous transition metal known for its strength-to-weight ratio and corrosion resistance. Widely used in aerospace, medical implants, and high-performance alloys."
  },
  {
    atomicNumber: 23,
    symbol: "V",
    name: "Vanadium",
    atomicWeight: 50.942,
    category: "transition-metal",
    electronConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d³ 4s²",
    electronegativity: 1.63,
    density: 6.11,
    meltingPoint: 1910,
    boilingPoint: 3407,
    discoveryYear: 1801,
    description: "Vanadium is a hard, silvery-grey metal with atomic number 23. It enhances steel's strength and durability and finds use in tools, construction, and energy storage."
  },
  {
    atomicNumber: 24,
    symbol: "Cr",
    name: "Chromium",
    atomicWeight: 51.996,
    category: "transition-metal",
    electronConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d⁵ 4s¹",
    electronegativity: 1.66,
    density: 7.19,
    meltingPoint: 1907,
    boilingPoint: 2671,
    discoveryYear: 1797,
    description: "Chromium is a lustrous, brittle transition metal known for its high polish and resistance to tarnish. It is used in stainless steel, plating, and dyes."
  },
  {
    atomicNumber: 25,
    symbol: "Mn",
    name: "Manganese",
    atomicWeight: 54.938,
    category: "transition-metal",
    electronConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d⁵ 4s²",
    electronegativity: 1.55,
    density: 7.21,
    meltingPoint: 1246,
    boilingPoint: 2061,
    discoveryYear: 1774,
    description: "Manganese is a gray-white metal used to improve the strength, toughness, and wear resistance of steel. It also plays a crucial biological role in enzyme systems."
  },
  {
    atomicNumber: 26,
    symbol: "Fe",
    name: "Iron",
    atomicWeight: 55.845,
    category: "transition-metal",
    electronConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d⁶",
    electronegativity: 1.83,
    density: 7.87,
    meltingPoint: 1538,
    boilingPoint: 2862,
    discoveryYear: "Ancient",
    description: "Iron is a chemical element with symbol Fe and atomic number 26. It is a metal in the first transition series. It is by mass the most common element on Earth, forming much of Earth's outer and inner core."
  },
  {
    atomicNumber: 27,
    symbol: "Co",
    name: "Cobalt",
    atomicWeight: 58.933,
    category: "transition-metal",
    electronConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d⁷ 4s²",
    electronegativity: 1.88,
    density: 8.90,
    meltingPoint: 1495,
    boilingPoint: 2927,
    discoveryYear: 1735,
    description: "Cobalt is a hard, lustrous, silver-gray metal used in magnets, high-strength alloys, and batteries. With atomic number 27, it also plays a vital role in vitamin B12."
  },
  {
    atomicNumber: 28,
    symbol: "Ni",
    name: "Nickel",
    atomicWeight: 58.693,
    category: "transition-metal",
    electronConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d⁸ 4s²",
    electronegativity: 1.91,
    density: 8.90,
    meltingPoint: 1455,
    boilingPoint: 2913,
    discoveryYear: 1751,
    description: "Nickel is a silvery-white metal with high polish and corrosion resistance. Found in coins, stainless steel, and batteries, it bears atomic number 28 and a quiet resilience."
  },
  {
    atomicNumber: 29,
    symbol: "Cu",
    name: "Copper",
    atomicWeight: 63.546,
    category: "transition-metal",
    electronConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s¹ 3d¹⁰",
    electronegativity: 1.90,
    density: 8.96,
    meltingPoint: 1084.62,
    boilingPoint: 2562,
    discoveryYear: "Ancient",
    description: "Copper is a chemical element with symbol Cu and atomic number 29. It is a soft, malleable, and ductile metal with very high thermal and electrical conductivity."
  },
  {
    atomicNumber: 30,
    symbol: "Zn",
    name: "Zinc",
    atomicWeight: 65.38,
    category: "transition-metal",
    electronConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s²",
    electronegativity: 1.65,
    density: 7.14,
    meltingPoint: 419.53,
    boilingPoint: 907,
    discoveryYear: "Ancient",
    description: "Zinc is a bluish-white metal known since antiquity, essential for human health and widely used in galvanization to prevent rust."
  },
  {
    atomicNumber: 31,
    symbol: "Ga",
    name: "Gallium",
    atomicWeight: 69.723,
    category: "post-transition-metal",
    electronConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p¹",
    electronegativity: 1.81,
    density: 5.91,
    meltingPoint: 29.76,
    boilingPoint: 2204,
    discoveryYear: 1875,
    description: "Gallium is a soft, silvery metal that melts just above room temperature. It is notable for its use in semiconductors and mirrors."
  },
  {
    atomicNumber: 32,
    symbol: "Ge",
    name: "Germanium",
    atomicWeight: 72.63,
    category: "metalloid",
    electronConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p²",
    electronegativity: 2.01,
    density: 5.32,
    meltingPoint: 938.3,
    boilingPoint: 2833,
    discoveryYear: 1886,
    description: "Germanium is a lustrous, hard metalloid used in semiconductors and fiber optics, bridging the gap between metals and nonmetals."
  },
  {
    atomicNumber: 33,
    symbol: "As",
    name: "Arsenic",
    atomicWeight: 74.922,
    category: "metalloid",
    electronConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p³",
    electronegativity: 2.18,
    density: 5.72,
    meltingPoint: 817,
    boilingPoint: 614,
    discoveryYear: "Ancient",
    description: "Arsenic is a notoriously toxic metalloid, historically used in pigments and pesticides. Its name evokes both danger and mystery."
  },
  {
    atomicNumber: 34,
    symbol: "Se",
    name: "Selenium",
    atomicWeight: 78.971,
    category: "nonmetal",
    electronConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁴",
    electronegativity: 2.55,
    density: 4.81,
    meltingPoint: 221,
    boilingPoint: 685,
    discoveryYear: 1817,
    description: "Selenium is a nonmetal essential in small amounts for life, yet toxic in larger doses. It is used in glassmaking and photocells."
  },
  {
    atomicNumber: 35,
    symbol: "Br",
    name: "Bromine",
    atomicWeight: 79.904,
    category: "halogen",
    electronConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁵",
    electronegativity: 2.96,
    density: 3.12,
    meltingPoint: -7.2,
    boilingPoint: 58.8,
    discoveryYear: 1826,
    description: "Bromine is a reddish-brown liquid halogen, known for its pungent odor and use in flame retardants and pharmaceuticals."
  },
  {
    atomicNumber: 36,
    symbol: "Kr",
    name: "Krypton",
    atomicWeight: 83.80,
    category: "noble-gas",
    electronConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶",
    electronegativity: 3.00,
    density: 0.003733,
    meltingPoint: -157.36,
    boilingPoint: -153.22,
    discoveryYear: 1898,
    description: "Krypton is a chemical element with symbol Kr and atomic number 36. It is a member of group 18 (noble gases) elements. A colorless, odorless, tasteless noble gas, krypton occurs in trace amounts in the atmosphere and is often used with other rare gases in fluorescent lamps."
  },
  {
    atomicNumber: 37,
    symbol: "Rb",
    name: "Rubidium",
    atomicWeight: 85.468,
    category: "alkali-metal",
    electronConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 5s¹",
    electronegativity: 0.82,
    density: 1.53,
    meltingPoint: 39.3,
    boilingPoint: 688,
    discoveryYear: 1861,
    description: "Rubidium is a soft, silvery-white alkali metal, highly reactive and used in research and atomic clocks."
  },
  {
    atomicNumber: 38,
    symbol: "Sr",
    name: "Strontium",
    atomicWeight: 87.62,
    category: "alkaline-earth-metal",
    electronConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 5s²",
    electronegativity: 0.95,
    density: 2.64,
    meltingPoint: 777,
    boilingPoint: 1382,
    discoveryYear: 1790,
    description: "Strontium is a soft, silvery alkaline earth metal, notable for its use in fireworks and ferrite magnets."
  },
  {
    atomicNumber: 39,
    symbol: "Y",
    name: "Yttrium",
    atomicWeight: 88.906,
    category: "transition-metal",
    electronConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹ 5s²",
    electronegativity: 1.22,
    density: 4.47,
    meltingPoint: 1526,
    boilingPoint: 3337,
    discoveryYear: 1794,
    description: "Yttrium is a silvery-metallic transition metal, often found in rare-earth minerals and used in LEDs and phosphors."
  },
  {
    atomicNumber: 40,
    symbol: "Zr",
    name: "Zirconium",
    atomicWeight: 91.224,
    category: "transition-metal",
    electronConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d² 5s²",
    electronegativity: 1.33,
    density: 6.52,
    meltingPoint: 1855,
    boilingPoint: 4409,
    discoveryYear: 1789,
    description: "Zirconium is a lustrous, grey-white transition metal, resistant to corrosion and used in nuclear reactors and surgical appliances."
  },
  {
    atomicNumber: 41,
    symbol: "Nb",
    name: "Niobium",
    atomicWeight: 92.906,
    category: "transition-metal",
    electronConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d⁴ 5s¹",
    electronegativity: 1.6,
    density: 8.57,
    meltingPoint: 2477,
    boilingPoint: 4744,
    discoveryYear: 1801,
    description: "Niobium is a soft, grey, ductile transition metal used in superconducting materials and aircraft engines."
  },
  {
    atomicNumber: 42,
    symbol: "Mo",
    name: "Molybdenum",
    atomicWeight: 95.95,
    category: "transition-metal",
    electronConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d⁵ 5s¹",
    electronegativity: 2.16,
    density: 10.28,
    meltingPoint: 2623,
    boilingPoint: 4639,
    discoveryYear: 1778,
    description: "Molybdenum is a silvery metal with a high melting point, essential in steel alloys and enzymes in biological systems."
  },
  {
    atomicNumber: 43,
    symbol: "Tc",
    name: "Technetium",
    atomicWeight: 98,
    category: "transition-metal",
    electronConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d⁵ 5s²",
    electronegativity: 1.9,
    density: 11.5,
    meltingPoint: 2157,
    boilingPoint: 4265,
    discoveryYear: 1937,
    description: "Technetium is the lightest element with no stable isotopes, used in medical diagnostic procedures."
  },
  {
    atomicNumber: 44,
    symbol: "Ru",
    name: "Ruthenium",
    atomicWeight: 101.07,
    category: "transition-metal",
    electronConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d⁷ 5s¹",
    electronegativity: 2.2,
    density: 12.45,
    meltingPoint: 2334,
    boilingPoint: 4150,
    discoveryYear: 1844,
    description: "Ruthenium is a rare transition metal, highly resistant to corrosion, used in electronics and catalysis."
  },
  {
    atomicNumber: 45,
    symbol: "Rh",
    name: "Rhodium",
    atomicWeight: 102.91,
    category: "transition-metal",
    electronConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d⁸ 5s¹",
    electronegativity: 2.28,
    density: 12.41,
    meltingPoint: 1964,
    boilingPoint: 3727,
    discoveryYear: 1803,
    description: "Rhodium is a rare, silvery-white metal known for its catalytic properties and resistance to corrosion."
  },
  {
    atomicNumber: 46,
    symbol: "Pd",
    name: "Palladium",
    atomicWeight: 106.42,
    category: "transition-metal",
    electronConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰",
    electronegativity: 2.20,
    density: 12.02,
    meltingPoint: 1555,
    boilingPoint: 2963,
    discoveryYear: 1803,
    description: "Palladium is a lustrous silver-white metal prized for its catalytic abilities and use in jewelry and electronics."
  },
  {
    atomicNumber: 47,
    symbol: "Ag",
    name: "Silver",
    atomicWeight: 107.87,
    category: "transition-metal",
    electronConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s¹ 4d¹⁰",
    electronegativity: 1.93,
    density: 10.49,
    meltingPoint: 961.78,
    boilingPoint: 2162,
    discoveryYear: "Ancient",
    description: "Silver is a chemical element with symbol Ag and atomic number 47. A soft, white, lustrous transition metal, it exhibits the highest electrical conductivity, thermal conductivity, and reflectivity of any metal."
  },
  {
    atomicNumber: 48,
    symbol: "Cd",
    name: "Cadmium",
    atomicWeight: 112.414,
    category: "transition-metal",
    electronConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰ 5s²",
    electronegativity: 1.69,
    density: 8.65,
    meltingPoint: 321.07,
    boilingPoint: 767,
    discoveryYear: 1817,
    description: "Cadmium is a soft, bluish-white metal primarily used in batteries, pigments, and coatings, though it demands careful handling due to its toxicity."
  },
  {
    atomicNumber: 49,
    symbol: "In",
    name: "Indium",
    atomicWeight: 114.818,
    category: "post-transition-metal",
    electronConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰ 5s² 5p¹",
    electronegativity: 1.78,
    density: 7.31,
    meltingPoint: 156.6,
    boilingPoint: 2072,
    discoveryYear: 1863,
    description: "Indium is a soft, malleable metal known for its low melting point and use in touchscreens, solders, and alloys."
  },
  {
    atomicNumber: 50,
    symbol: "Sn",
    name: "Tin",
    atomicWeight: 118.71,
    category: "post-transition-metal",
    electronConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p²",
    electronegativity: 1.96,
    density: 7.31,
    meltingPoint: 231.93,
    boilingPoint: 2602,
    discoveryYear: "Ancient",
    description: "Tin is a chemical element with symbol Sn and atomic number 50. It is a post-transition metal in group 14 of the periodic table. It is obtained chiefly from the mineral cassiterite, which contains tin dioxide, SnO₂."
  },
  {
    atomicNumber: 51,
    symbol: "Sb",
    name: "Antimony",
    atomicWeight: 121.76,
    category: "metalloid",
    electronConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰ 5s² 5p³",
    electronegativity: 2.05,
    density: 6.697,
    meltingPoint: 630.63,
    boilingPoint: 1587,
    discoveryYear: "Ancient",
    description: "Antimony is a lustrous metalloid used since antiquity in alloys, flame retardants, and medicine, often cloaked in alchemical symbolism."
  },
  {
    atomicNumber: 52,
    symbol: "Te",
    name: "Tellurium",
    atomicWeight: 127.60,
    category: "metalloid",
    electronConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰ 5s² 5p⁴",
    electronegativity: 2.1,
    density: 6.24,
    meltingPoint: 722.66,
    boilingPoint: 1261,
    discoveryYear: 1782,
    description: "Tellurium is a rare metalloid, cherished in metallurgy and semiconductor technology, with a subtle sheen and storied past."
  },
  {
    atomicNumber: 53,
    symbol: "I",
    name: "Iodine",
    atomicWeight: 126.904,
    category: "halogen",
    electronConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰ 5s² 5p⁵",
    electronegativity: 2.66,
    density: 4.93,
    meltingPoint: 113.7,
    boilingPoint: 184.3,
    discoveryYear: 1811,
    description: "Iodine is a lustrous, violet-black halogen, essential in medicine and photography, its vapor a swirling purple haze."
  },
  {
    atomicNumber: 54,
    symbol: "Xe",
    name: "Xenon",
    atomicWeight: 131.293,
    category: "noble-gas",
    electronConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰ 5s² 5p⁶",
    electronegativity: 2.6,
    density: 5.9,
    meltingPoint: -111.8,
    boilingPoint: -108.1,
    discoveryYear: 1898,
    description: "Xenon is a rare noble gas with noble silence, used in lighting, anesthesia, and high-performance imaging."
  },
  {
    atomicNumber: 55,
    symbol: "Cs",
    name: "Cesium",
    atomicWeight: 132.905,
    category: "alkali-metal",
    electronConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰ 5s² 5p⁶ 6s¹",
    electronegativity: 0.79,
    density: 1.93,
    meltingPoint: 28.44,
    boilingPoint: 671,
    discoveryYear: 1860,
    description: "Cesium is a soft, golden alkali metal, notable for its use in atomic clocks, defining the very flow of time."
  },
  {
    atomicNumber: 56,
    symbol: "Ba",
    name: "Barium",
    atomicWeight: 137.327,
    category: "alkaline-earth-metal",
    electronConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰ 5s² 5p⁶ 6s²",
    electronegativity: 0.89,
    density: 3.62,
    meltingPoint: 727,
    boilingPoint: 1845,
    discoveryYear: 1808,
    description: "Barium is a soft, silvery alkaline earth metal, known for its bright green flame and use in medical imaging."
  },
  {
    atomicNumber: 57,
    symbol: "La",
    name: "Lanthanum",
    atomicWeight: 138.905,
    category: "lanthanide",
    electronConfiguration: "[Xe] 5d¹ 6s²",
    electronegativity: 1.1,
    density: 6.15,
    meltingPoint: 920,
    boilingPoint: 3464,
    discoveryYear: 1839,
    description: "Lanthanum, the first of the lanthanides, is a soft, silvery metal with roles in optics and catalysts."
  },
  {
    atomicNumber: 58,
    symbol: "Ce",
    name: "Cerium",
    atomicWeight: 140.116,
    category: "lanthanide",
    electronConfiguration: "[Xe] 4f¹ 5d¹ 6s²",
    electronegativity: 1.12,
    density: 6.77,
    meltingPoint: 795,
    boilingPoint: 3443,
    discoveryYear: 1839,
    description: "Cerium is a lustrous lanthanide, vital for catalytic converters and polishing powders."
  },
  {
    atomicNumber: 59,
    symbol: "Pr",
    name: "Praseodymium",
    atomicWeight: 140.908,
    category: "lanthanide",
    electronConfiguration: "[Xe] 4f³ 6s²",
    electronegativity: 1.13,
    density: 6.77,
    meltingPoint: 931,
    boilingPoint: 3520,
    discoveryYear: 1885,
    description: "Praseodymium is a soft, silvery lanthanide used in magnets, glasses, and lighting."
  },
  {
    atomicNumber: 60,
    symbol: "Nd",
    name: "Neodymium",
    atomicWeight: 144.242,
    category: "lanthanide",
    electronConfiguration: "[Xe] 4f⁴ 6s²",
    electronegativity: 1.14,
    density: 7.01,
    meltingPoint: 1024,
    boilingPoint: 3074,
    discoveryYear: 1885,
    description: "Neodymium is a lustrous metal prized for powerful magnets essential in modern technology."
  },
  {
    atomicNumber: 61,
    symbol: "Pm",
    name: "Promethium",
    atomicWeight: 145,
    category: "lanthanide",
    electronConfiguration: "[Xe] 4f⁵ 6s²",
    electronegativity: 1.13,
    density: 7.26,
    meltingPoint: 1042,
    boilingPoint: 3000,
    discoveryYear: 1945,
    description: "Promethium is a rare, radioactive lanthanide, found only in trace amounts and used in luminous paint and nuclear batteries."
  },
  {
    atomicNumber: 62,
    symbol: "Sm",
    name: "Samarium",
    atomicWeight: 150.36,
    category: "lanthanide",
    electronConfiguration: "[Xe] 4f⁶ 6s²",
    electronegativity: 1.17,
    density: 7.52,
    meltingPoint: 1072,
    boilingPoint: 1794,
    discoveryYear: 1879,
    description: "Samarium is a hard, silvery lanthanide used in magnets and cancer treatment."
  },
  {
    atomicNumber: 63,
    symbol: "Eu",
    name: "Europium",
    atomicWeight: 151.964,
    category: "lanthanide",
    electronConfiguration: "[Xe] 4f⁷ 6s²",
    electronegativity: 1.2,
    density: 5.24,
    meltingPoint: 822,
    boilingPoint: 1597,
    discoveryYear: 1901,
    description: "Europium is a soft, silvery lanthanide famed for its use in red phosphors for television and LED screens."
  },
  {
    atomicNumber: 64,
    symbol: "Gd",
    name: "Gadolinium",
    atomicWeight: 157.25,
    category: "lanthanide",
    electronConfiguration: "[Xe] 4f⁷ 5d¹ 6s²",
    electronegativity: 1.2,
    density: 7.9,
    meltingPoint: 1313,
    boilingPoint: 3273,
    discoveryYear: 1880,
    description: "Gadolinium is a silvery lanthanide used in MRI contrast agents and neutron radiography."
  },
  {
    atomicNumber: 65,
    symbol: "Tb",
    name: "Terbium",
    atomicWeight: 158.925,
    category: "lanthanide",
    electronConfiguration: "[Xe] 4f⁹ 6s²",
    electronegativity: 1.2,
    density: 8.23,
    meltingPoint: 1629,
    boilingPoint: 3503,
    discoveryYear: 1843,
    description: "Terbium is a rare lanthanide used in solid-state devices and green phosphors."
  },
  {
    atomicNumber: 66,
    symbol: "Dy",
    name: "Dysprosium",
    atomicWeight: 162.5,
    category: "lanthanide",
    electronConfiguration: "[Xe] 4f¹⁰ 6s²",
    electronegativity: 1.22,
    density: 8.55,
    meltingPoint: 1680,
    boilingPoint: 2840,
    discoveryYear: 1886,
    description: "Dysprosium is a rare earth metal used in magnets, lasers, and nuclear reactors."
  },
  {
    atomicNumber: 67,
    symbol: "Ho",
    name: "Holmium",
    atomicWeight: 164.93,
    category: "lanthanide",
    electronConfiguration: "[Xe] 4f¹¹ 6s²",
    electronegativity: 1.23,
    density: 8.79,
    meltingPoint: 1747,
    boilingPoint: 2700,
    discoveryYear: 1878,
    description: "Holmium is a soft, malleable lanthanide with the highest magnetic moment of any element."
  },
  {
    atomicNumber: 68,
    symbol: "Er",
    name: "Erbium",
    atomicWeight: 167.26,
    category: "lanthanide",
    electronConfiguration: "[Xe] 4f¹² 6s²",
    electronegativity: 1.24,
    density: 9.07,
    meltingPoint: 1529,
    boilingPoint: 2868,
    discoveryYear: 1843,
    description: "Erbium is a soft, malleable, silvery-white metal that is a member of the lanthanide series of rare earth elements."
  },
{
  "atomicNumber": 69,
  "symbol": "Tm",
  "name": "Thulium",
  "atomicWeight": 168.93,
  "category": "lanthanide",
  "electronConfiguration": "[Xe] 4f¹³ 6s²",
  "electronegativity": 1.25,
  "density": 9.32,
  "meltingPoint": 1545,
  "boilingPoint": 1950,
  "discoveryYear": 1879,
  "description": "Thulium is the rarest naturally occurring lanthanide, used in portable X-ray devices."
},
{
  "atomicNumber": 70,
  "symbol": "Yb",
  "name": "Ytterbium",
  "atomicWeight": 173.045,
  "category": "lanthanide",
  "electronConfiguration": "[Xe] 4f¹⁴ 6s²",
  "electronegativity": 1.1,
  "density": 6.97,
  "meltingPoint": 824,
  "boilingPoint": 1196,
  "discoveryYear": 1878,
  "description": "Ytterbium is a soft lanthanide used in lasers and atomic clocks."
},
{
  "atomicNumber": 71,
  "symbol": "Lu",
  "name": "Lutetium",
  "atomicWeight": 174.967,
  "category": "lanthanide",
  "electronConfiguration": "[Xe] 4f¹⁴ 5d¹ 6s²",
  "electronegativity": 1.27,
  "density": 9.84,
  "meltingPoint": 1663,
  "boilingPoint": 3402,
  "discoveryYear": 1907,
  "description": "Lutetium is the densest and hardest lanthanide, used in PET scan detectors and catalysts."
},
{
  "atomicNumber": 72,
  "symbol": "Hf",
  "name": "Hafnium",
  "atomicWeight": 178.49,
  "category": "transition-metal",
  "electronConfiguration": "[Xe] 4f¹⁴ 5d² 6s²",
  "electronegativity": 1.3,
  "density": 13.31,
  "meltingPoint": 2233,
  "boilingPoint": 4603,
  "discoveryYear": 1923,
  "description": "Hafnium is a corrosion-resistant transition metal used in nuclear reactors and aerospace alloys."
},
{
  "atomicNumber": 73,
  "symbol": "Ta",
  "name": "Tantalum",
  "atomicWeight": 180.948,
  "category": "transition-metal",
  "electronConfiguration": "[Xe] 4f¹⁴ 5d³ 6s²",
  "electronegativity": 1.5,
  "density": 16.69,
  "meltingPoint": 3017,
  "boilingPoint": 5458,
  "discoveryYear": 1802,
  "description": "Tantalum is a highly corrosion-resistant metal used in electronics, surgical instruments, and capacitors."
},
{
  "atomicNumber": 74,
  "symbol": "W",
  "name": "Tungsten",
  "atomicWeight": 183.84,
  "category": "transition-metal",
  "electronConfiguration": "[Xe] 4f¹⁴ 5d⁴ 6s²",
  "electronegativity": 2.36,
  "density": 19.25,
  "meltingPoint": 3422,
  "boilingPoint": 5555,
  "discoveryYear": 1783,
  "description": "Tungsten is renowned for its extraordinary hardness and highest melting point among metals."
},
{
  "atomicNumber": 75,
  "symbol": "Re",
  "name": "Rhenium",
  "atomicWeight": 186.207,
  "category": "transition-metal",
  "electronConfiguration": "[Xe] 4f¹⁴ 5d⁵ 6s²",
  "electronegativity": 1.9,
  "density": 21.02,
  "meltingPoint": 3186,
  "boilingPoint": 5596,
  "discoveryYear": 1925,
  "description": "Rhenium is a rare, dense metal used in high-temperature turbine engines and catalysts."
},
{
  "atomicNumber": 76,
  "symbol": "Os",
  "name": "Osmium",
  "atomicWeight": 190.23,
  "category": "transition-metal",
  "electronConfiguration": "[Xe] 4f¹⁴ 5d⁶ 6s²",
  "electronegativity": 2.2,
  "density": 22.59,
  "meltingPoint": 3045,
  "boilingPoint": 5027,
  "discoveryYear": 1803,
  "description": "Osmium is the densest naturally occurring element, a bluish metal with remarkable hardness and high melting point."
},
{
  "atomicNumber": 77,
  "symbol": "Ir",
  "name": "Iridium",
  "atomicWeight": 192.217,
  "category": "transition-metal",
  "electronConfiguration": "[Xe] 4f¹⁴ 5d⁷ 6s²",
  "electronegativity": 2.20,
  "density": 22.56,
  "meltingPoint": 2466,
  "boilingPoint": 4130,
  "discoveryYear": 1803,
  "description": "Iridium is a rare, extremely corrosion-resistant metal, often used in high-temperature and electrical applications."
},
{
  "atomicNumber": 78,
  "symbol": "Pt",
  "name": "Platinum",
  "atomicWeight": 195.084,
  "category": "transition-metal",
  "electronConfiguration": "[Xe] 4f¹⁴ 5d⁹ 6s¹",
  "electronegativity": 2.28,
  "density": 21.45,
  "meltingPoint": 1768,
  "boilingPoint": 3825,
  "discoveryYear": "Ancient",
  "description": "Platinum is a precious metal admired for its resistance to corrosion and catalytic properties."
},
{
  "atomicNumber": 79,
  "symbol": "Au",
  "name": "Gold",
  "atomicWeight": 196.967,
  "category": "transition-metal",
  "electronConfiguration": "[Xe] 4f¹⁴ 5d¹⁰ 6s¹",
  "electronegativity": 2.54,
  "density": 19.32,
  "meltingPoint": 1064,
  "boilingPoint": 2856,
  "discoveryYear": "Ancient",
  "description": "Gold is the eternal symbol of wealth and beauty, a noble metal of unmatched luster and malleability."
},
{
  "atomicNumber": 80,
  "symbol": "Hg",
  "name": "Mercury",
  "atomicWeight": 200.592,
  "category": "transition-metal",
  "electronConfiguration": "[Xe] 4f¹⁴ 5d¹⁰ 6s²",
  "electronegativity": 2.00,
  "density": 13.534,
  "meltingPoint": -38.83,
  "boilingPoint": 356.73,
  "discoveryYear": "Ancient",
  "description": "Mercury, the only metallic element liquid at room temperature, is steeped in history and mystique."
},

  {
  "atomicNumber": 81,
  "symbol": "Tl",
  "name": "Thallium",
  "atomicWeight": 204.38,
  "category": "post-transition-metal",
  "electronConfiguration": "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p¹",
  "electronegativity": 1.62,
  "density": 11.85,
  "meltingPoint": 304,
  "boilingPoint": 1473,
  "discoveryYear": 1861,
  "description": "Thallium is a soft, malleable metal used in electronics and historically in rat poison."
},
{
  "atomicNumber": 82,
  "symbol": "Pb",
  "name": "Lead",
  "atomicWeight": 207.2,
  "category": "post-transition-metal",
  "electronConfiguration": "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p²",
  "electronegativity": 2.33,
  "density": 11.34,
  "meltingPoint": 327.46,
  "boilingPoint": 1749,
  "discoveryYear": "Ancient",
  "description": "Lead is a heavy, soft metal historically used in pipes, paints, and batteries but toxic to humans."
},
{
  "atomicNumber": 83,
  "symbol": "Bi",
  "name": "Bismuth",
  "atomicWeight": 208.980,
  "category": "post-transition-metal",
  "electronConfiguration": "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p³",
  "electronegativity": 2.02,
  "density": 9.78,
  "meltingPoint": 271.4,
  "boilingPoint": 1564,
  "discoveryYear": "Ancient",
  "description": "Bismuth is a brittle, low-toxicity metal used in cosmetics, pharmaceuticals, and alloys."
},
{
  "atomicNumber": 84,
  "symbol": "Po",
  "name": "Polonium",
  "atomicWeight": 209,
  "category": "post-transition-metal",
  "electronConfiguration": "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁴",
  "electronegativity": 2.0,
  "density": 9.32,
  "meltingPoint": 254,
  "boilingPoint": 962,
  "discoveryYear": 1898,
  "description": "Polonium is a rare, highly radioactive metal discovered by Marie Curie, used in antistatic devices."
},
{
  "atomicNumber": 85,
  "symbol": "At",
  "name": "Astatine",
  "atomicWeight": 210,
  "category": "halogen",
  "electronConfiguration": "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁵",
  "electronegativity": 2.2,
  "density": 7,
  "meltingPoint": 302,
  "boilingPoint": 610,
  "discoveryYear": 1940,
  "description": "Astatine is a rare and highly radioactive halogen with very limited practical applications."
},
{
  "atomicNumber": 86,
  "symbol": "Rn",
  "name": "Radon",
  "atomicWeight": 222,
  "category": "noble-gas",
  "electronConfiguration": "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁶",
  "electronegativity": 2.2,
  "density": 9.73,
  "meltingPoint": -71,
  "boilingPoint": -62,
  "discoveryYear": 1900,
  "description": "Radon is a radioactive noble gas known for its role in indoor air quality and lung cancer risk."
},
{
  "atomicNumber": 87,
  "symbol": "Fr",
  "name": "Francium",
  "atomicWeight": 223,
  "category": "alkali-metal",
  "electronConfiguration": "[Rn] 7s¹",
  "electronegativity": 0.7,
  "density": 1.87,
  "meltingPoint": 27,
  "boilingPoint": 677,
  "discoveryYear": 1939,
  "description": "Francium is a highly radioactive, extremely rare alkali metal with no commercial applications."
},
{
  "atomicNumber": 88,
  "symbol": "Ra",
  "name": "Radium",
  "atomicWeight": 226,
  "category": "alkaline-earth-metal",
  "electronConfiguration": "[Rn] 7s²",
  "electronegativity": 0.9,
  "density": 5.5,
  "meltingPoint": 700,
  "boilingPoint": 1737,
  "discoveryYear": 1898,
  "description": "Radium is a radioactive alkaline earth metal once used in luminous paints and cancer treatment."
},
{
  "atomicNumber": 89,
  "symbol": "Ac",
  "name": "Actinium",
  "atomicWeight": 227,
  "category": "actinide",
  "electronConfiguration": "[Rn] 6d¹ 7s²",
  "electronegativity": 1.1,
  "density": 10.07,
  "meltingPoint": 1050,
  "boilingPoint": 3200,
  "discoveryYear": 1899,
  "description": "Actinium is a radioactive actinide metal used as a neutron source."
},
{
  "atomicNumber": 90,
  "symbol": "Th",
  "name": "Thorium",
  "atomicWeight": 232.0377,
  "category": "actinide",
  "electronConfiguration": "[Rn] 6d² 7s²",
  "electronegativity": 1.3,
  "density": 11.72,
  "meltingPoint": 1750,
  "boilingPoint": 4820,
  "discoveryYear": 1829,
  "description": "Thorium is a radioactive actinide considered for nuclear fuel and high-temperature ceramics."
},
{
  "atomicNumber": 91,
  "symbol": "Pa",
  "name": "Protactinium",
  "atomicWeight": 231.0359,
  "category": "actinide",
  "electronConfiguration": "[Rn] 5f² 6d¹ 7s²",
  "electronegativity": 1.5,
  "density": 15.37,
  "meltingPoint": 1572,
  "boilingPoint": 4273,
  "discoveryYear": 1917,
  "description": "Protactinium is a dense, radioactive metal with limited research use."
},
{
  "atomicNumber": 92,
  "symbol": "U",
  "name": "Uranium",
  "atomicWeight": 238.0289,
  "category": "actinide",
  "electronConfiguration": "[Rn] 5f³ 6d¹ 7s²",
  "electronegativity": 1.38,
  "density": 19.1,
  "meltingPoint": 1135,
  "boilingPoint": 4131,
  "discoveryYear": 1789,
  "description": "Uranium is a heavy radioactive metal widely used as fuel in nuclear reactors and weapons."
},
{
  "atomicNumber": 93,
  "symbol": "Np",
  "name": "Neptunium",
  "atomicWeight": 237,
  "category": "actinide",
  "electronConfiguration": "[Rn] 5f⁴ 6d¹ 7s²",
  "electronegativity": 1.36,
  "density": 20.45,
  "meltingPoint": 912,
  "boilingPoint": 4273,
  "discoveryYear": 1940,
  "description": "Neptunium is a radioactive actinide used in research and as a precursor to plutonium."
},
{
  "atomicNumber": 94,
  "symbol": "Pu",
  "name": "Plutonium",
  "atomicWeight": 244,
  "category": "actinide",
  "electronConfiguration": "[Rn] 5f⁶ 7s²",
  "electronegativity": 1.28,
  "density": 19.84,
  "meltingPoint": 913,
  "boilingPoint": 3505,
  "discoveryYear": 1940,
  "description": "Plutonium is a radioactive actinide key to nuclear weapons and reactors."
},
{
  "atomicNumber": 95,
  "symbol": "Am",
  "name": "Americium",
  "atomicWeight": 243,
  "category": "actinide",
  "electronConfiguration": "[Rn] 5f⁷ 7s²",
  "electronegativity": 1.3,
  "density": 13.67,
  "meltingPoint": 1449,
  "boilingPoint": 2880,
  "discoveryYear": 1944,
  "description": "Americium is used in smoke detectors and industrial gauges."
},
{
  "atomicNumber": 96,
  "symbol": "Cm",
  "name": "Curium",
  "atomicWeight": 247,
  "category": "actinide",
  "electronConfiguration": "[Rn] 5f⁷ 6d¹ 7s²",
  "electronegativity": 1.3,
  "density": 13.51,
  "meltingPoint": 1340,
  "boilingPoint": 3110,
  "discoveryYear": 1944,
  "description": "Curium is a radioactive actinide used in scientific research."
},
{
  "atomicNumber": 97,
  "symbol": "Bk",
  "name": "Berkelium",
  "atomicWeight": 247,
  "category": "actinide",
  "electronConfiguration": "[Rn] 5f⁹ 7s²",
  "electronegativity": 1.3,
  "density": 14.78,
  "meltingPoint": 1259,
  "boilingPoint": 2900,
  "discoveryYear": 1949,
  "description": "Berkelium is a synthetic radioactive element with limited applications."
},
{
  "atomicNumber": 98,
  "symbol": "Cf",
  "name": "Californium",
  "atomicWeight": 251,
  "category": "actinide",
  "electronConfiguration": "[Rn] 5f¹⁰ 7s²",
  "electronegativity": 1.3,
  "density": 15.1,
  "meltingPoint": 900,
  "boilingPoint": 1470,
  "discoveryYear": 1950,
  "description": "Californium is a radioactive element used in neutron sources."
},
{
  "atomicNumber": 99,
  "symbol": "Es",
  "name": "Einsteinium",
  "atomicWeight": 252,
  "category": "actinide",
  "electronConfiguration": "[Rn] 5f¹¹ 7s²",
  "electronegativity": 1.3,
  "density": 8.84,
  "meltingPoint": 860,
  "boilingPoint": 996,
  "discoveryYear": 1952,
  "description": "Einsteinium is a synthetic, highly radioactive element named after Albert Einstein."
},
{
  "atomicNumber": 100,
  "symbol": "Fm",
  "name": "Fermium",
  "atomicWeight": 257,
  "category": "actinide",
  "electronConfiguration": "[Rn] 5f¹² 7s²",
  "electronegativity": 1.3,
  "density": 9.7,
  "meltingPoint": 1527,
  "boilingPoint": 3000,
  "discoveryYear": 1952,
  "description": "Fermium is a synthetic actinide discovered in the debris of a hydrogen bomb explosion."
},{
  "atomicNumber": 101,
  "symbol": "Md",
  "name": "Mendelevium",
  "atomicWeight": 258,
  "category": "actinide",
  "electronConfiguration": "[Rn] 5f¹³ 7s²",
  "electronegativity": 1.3,
  "density": 23.2,
  "meltingPoint": null,
  "boilingPoint": null,
  "discoveryYear": 1955,
  "description": "Mendelevium is a synthetic radioactive element named after Dmitri Mendeleev, the father of the periodic table."
},
{
  "atomicNumber": 102,
  "symbol": "No",
  "name": "Nobelium",
  "atomicWeight": 259,
  "category": "actinide",
  "electronConfiguration": "[Rn] 5f¹⁴ 7s²",
  "electronegativity": 1.3,
  "density": 9.9,
  "meltingPoint": null,
  "boilingPoint": null,
  "discoveryYear": 1958,
  "description": "Nobelium is a synthetic element named after Alfred Nobel, known for its radioactive properties."
},
{
  "atomicNumber": 103,
  "symbol": "Lr",
  "name": "Lawrencium",
  "atomicWeight": 262,
  "category": "actinide",
  "electronConfiguration": "[Rn] 5f¹⁴ 7s² 7p¹",
  "electronegativity": 1.3,
  "density": 15.6,
  "meltingPoint": null,
  "boilingPoint": null,
  "discoveryYear": 1961,
  "description": "Lawrencium is a synthetic element named after Ernest O. Lawrence, inventor of the cyclotron."
},
{
  "atomicNumber": 104,
  "symbol": "Rf",
  "name": "Rutherfordium",
  "atomicWeight": 267,
  "category": "transition-metal",
  "electronConfiguration": "[Rn] 5f¹⁴ 6d² 7s²",
  "electronegativity": null,
  "density": null,
  "meltingPoint": null,
  "boilingPoint": null,
  "discoveryYear": 1964,
  "description": "Rutherfordium is a synthetic element named in honor of Ernest Rutherford, pioneer of nuclear physics."
},
{
  "atomicNumber": 105,
  "symbol": "Db",
  "name": "Dubnium",
  "atomicWeight": 268,
  "category": "transition-metal",
  "electronConfiguration": "[Rn] 5f¹⁴ 6d³ 7s²",
  "electronegativity": null,
  "density": null,
  "meltingPoint": null,
  "boilingPoint": null,
  "discoveryYear": 1967,
  "description": "Dubnium is a synthetic element named after Dubna, Russia, where it was discovered."
},
{
  "atomicNumber": 106,
  "symbol": "Sg",
  "name": "Seaborgium",
  "atomicWeight": 271,
  "category": "transition-metal",
  "electronConfiguration": "[Rn] 5f¹⁴ 6d⁴ 7s²",
  "electronegativity": null,
  "density": null,
  "meltingPoint": null,
  "boilingPoint": null,
  "discoveryYear": 1974,
  "description": "Seaborgium is a synthetic element named for Glenn T. Seaborg, a pioneer in actinide research."
},
{
  "atomicNumber": 107,
  "symbol": "Bh",
  "name": "Bohrium",
  "atomicWeight": 270,
  "category": "transition-metal",
  "electronConfiguration": "[Rn] 5f¹⁴ 6d⁵ 7s²",
  "electronegativity": null,
  "density": null,
  "meltingPoint": null,
  "boilingPoint": null,
  "discoveryYear": 1981,
  "description": "Bohrium is a synthetic element named after physicist Niels Bohr."
},
{
  "atomicNumber": 108,
  "symbol": "Hs",
  "name": "Hassium",
  "atomicWeight": 277,
  "category": "transition-metal",
  "electronConfiguration": "[Rn] 5f¹⁴ 6d⁶ 7s²",
  "electronegativity": null,
  "density": null,
  "meltingPoint": null,
  "boilingPoint": null,
  "discoveryYear": 1984,
  "description": "Hassium is a synthetic element named after the German state of Hesse."
},
{
  "atomicNumber": 109,
  "symbol": "Mt",
  "name": "Meitnerium",
  "atomicWeight": 278,
  "category": "transition-metal",
  "electronConfiguration": "[Rn] 5f¹⁴ 6d⁷ 7s²",
  "electronegativity": null,
  "density": null,
  "meltingPoint": null,
  "boilingPoint": null,
  "discoveryYear": 1982,
  "description": "Meitnerium is a synthetic element named after physicist Lise Meitner."
},
{
  "atomicNumber": 110,
  "symbol": "Ds",
  "name": "Darmstadtium",
  "atomicWeight": 281,
  "category": "transition-metal",
  "electronConfiguration": "[Rn] 5f¹⁴ 6d⁹ 7s¹",
  "electronegativity": null,
  "density": null,
  "meltingPoint": null,
  "boilingPoint": null,
  "discoveryYear": 1994,
  "description": "Darmstadtium is a synthetic element named after Darmstadt, Germany."
},
{
  "atomicNumber": 111,
  "symbol": "Rg",
  "name": "Roentgenium",
  "atomicWeight": 282,
  "category": "transition-metal",
  "electronConfiguration": "[Rn] 5f¹⁴ 6d¹⁰ 7s¹",
  "electronegativity": null,
  "density": null,
  "meltingPoint": null,
  "boilingPoint": null,
  "discoveryYear": 1994,
  "description": "Roentgenium is a synthetic element named after Wilhelm Röntgen, discoverer of X-rays."
},
{
  "atomicNumber": 112,
  "symbol": "Cn",
  "name": "Copernicium",
  "atomicWeight": 285,
  "category": "transition-metal",
  "electronConfiguration": "[Rn] 5f¹⁴ 6d¹⁰ 7s²",
  "electronegativity": null,
  "density": null,
  "meltingPoint": null,
  "boilingPoint": null,
  "discoveryYear": 1996,
  "description": "Copernicium is a synthetic element named after Nicolaus Copernicus."
},
{
  "atomicNumber": 113,
  "symbol": "Nh",
  "name": "Nihonium",
  "atomicWeight": 286,
  "category": "post-transition-metal",
  "electronConfiguration": "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p¹",
  "electronegativity": null,
  "density": null,
  "meltingPoint": null,
  "boilingPoint": null,
  "discoveryYear": 2004,
  "description": "Nihonium is a synthetic element named after Japan ('Nihon')."
},
{
  "atomicNumber": 114,
  "symbol": "Fl",
  "name": "Flerovium",
  "atomicWeight": 289,
  "category": "post-transition-metal",
  "electronConfiguration": "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p²",
  "electronegativity": null,
  "density": null,
  "meltingPoint": null,
  "boilingPoint": null,
  "discoveryYear": 1998,
  "description": "Flerovium is a synthetic element named after the Flerov Laboratory of Nuclear Reactions."
},
{
  "atomicNumber": 115,
  "symbol": "Mc",
  "name": "Moscovium",
  "atomicWeight": 288,
  "category": "post-transition-metal",
  "electronConfiguration": "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p³",
  "electronegativity": null,
  "density": null,
  "meltingPoint": null,
  "boilingPoint": null,
  "discoveryYear": 2003,
  "description": "Moscovium is a synthetic element named after Moscow Oblast, Russia."
},
{
  "atomicNumber": 116,
  "symbol": "Lv",
  "name": "Livermorium",
  "atomicWeight": 293,
  "category": "post-transition-metal",
  "electronConfiguration": "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁴",
  "electronegativity": null,
  "density": null,
  "meltingPoint": null,
  "boilingPoint": null,
  "discoveryYear": 2000,
  "description": "Livermorium is a synthetic element named after Lawrence Livermore National Laboratory."
},
{
  "atomicNumber": 117,
  "symbol": "Ts",
  "name": "Tennessine",
  "atomicWeight": 294,
  "category": "halogen",
  "electronConfiguration": "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁵",
  "electronegativity": null,
  "density": null,
  "meltingPoint": null,
  "boilingPoint": null,
  "discoveryYear": 2010,
  "description": "Tennessine is a synthetic halogen named after the state of Tennessee."
},
{
  "atomicNumber": 118,
  "symbol": "Og",
  "name": "Oganesson",
  "atomicWeight": 294,
  "category": "noble-gas",
  "electronConfiguration": "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁶",
  "electronegativity": null,
  "density": null,
  "meltingPoint": null,
  "boilingPoint": null,
  "discoveryYear": 2002,
  "description": "Oganesson is a synthetic noble gas named in honor of Yuri Oganessian."
}

  // Note: This is a subset of elements for demonstration
  // A complete implementation would include all 118 elements
];

// Generate layout positions for elements in the periodic table
const elementPositions = {
  // Row 1
  1: { row: 1, col: 1 },
  2: { row: 1, col: 18 },

  // Row 2
  3: { row: 2, col: 1 },
  4: { row: 2, col: 2 },
  5: { row: 2, col: 13 },
  6: { row: 2, col: 14 },
  7: { row: 2, col: 15 },
  8: { row: 2, col: 16 },
  9: { row: 2, col: 17 },
  10: { row: 2, col: 18 },

  // Row 3
  11: { row: 3, col: 1 },
  12: { row: 3, col: 2 },
  13: { row: 3, col: 13 },
  14: { row: 3, col: 14 },
  15: { row: 3, col: 15 },
  16: { row: 3, col: 16 },
  17: { row: 3, col: 17 },
  18: { row: 3, col: 18 },

  // Row 4
  19: { row: 4, col: 1 },
  20: { row: 4, col: 2 },
  21: { row: 4, col: 3 },
  22: { row: 4, col: 4 },
  23: { row: 4, col: 5 },
  24: { row: 4, col: 6 },
  25: { row: 4, col: 7 },
  26: { row: 4, col: 8 },
  27: { row: 4, col: 9 },
  28: { row: 4, col: 10 },
  29: { row: 4, col: 11 },
  30: { row: 4, col: 12 },
  31: { row: 4, col: 13 },
  32: { row: 4, col: 14 },
  33: { row: 4, col: 15 },
  34: { row: 4, col: 16 },
  35: { row: 4, col: 17 },
  36: { row: 4, col: 18 },

  // Row 5
  37: { row: 5, col: 1 },
  38: { row: 5, col: 2 },
  39: { row: 5, col: 3 },
  40: { row: 5, col: 4 },
  41: { row: 5, col: 5 },
  42: { row: 5, col: 6 },
  43: { row: 5, col: 7 },
  44: { row: 5, col: 8 },
  45: { row: 5, col: 9 },
  46: { row: 5, col: 10 },
  47: { row: 5, col: 11 },
  48: { row: 5, col: 12 },
  49: { row: 5, col: 13 },
  50: { row: 5, col: 14 },
  51: { row: 5, col: 15 },
  52: { row: 5, col: 16 },
  53: { row: 5, col: 17 },
  54: { row: 5, col: 18 },

  // Row 6 (main table)
  55: { row: 6, col: 1 },
  56: { row: 6, col: 2 },
  57: { row: 6, col: 3 }, // La
  72: { row: 6, col: 4 },
  73: { row: 6, col: 5 },
  74: { row: 6, col: 6 },
  75: { row: 6, col: 7 },
  76: { row: 6, col: 8 },
  77: { row: 6, col: 9 },
  78: { row: 6, col: 10 },
  79: { row: 6, col: 11 },
  80: { row: 6, col: 12 },
  81: { row: 6, col: 13 },
  82: { row: 6, col: 14 },
  83: { row: 6, col: 15 },
  84: { row: 6, col: 16 },
  85: { row: 6, col: 17 },
  86: { row: 6, col: 18 },

  // Row 7 (main table)
  87: { row: 7, col: 1 },
  88: { row: 7, col: 2 },
  89: { row: 7, col: 3 }, // Ac
  104: { row: 7, col: 4 },
  105: { row: 7, col: 5 },
  106: { row: 7, col: 6 },
  107: { row: 7, col: 7 },
  108: { row: 7, col: 8 },
  109: { row: 7, col: 9 },
  110: { row: 7, col: 10 },
  111: { row: 7, col: 11 },
  112: { row: 7, col: 12 },
  113: { row: 7, col: 13 },
  114: { row: 7, col: 14 },
  115: { row: 7, col: 15 },
  116: { row: 7, col: 16 },
  117: { row: 7, col: 17 },
  118: { row: 7, col: 18 },

  // Lanthanides (Row 8, f-block)
  58: { row: 8, col: 4 },
  59: { row: 8, col: 5 },
  60: { row: 8, col: 6 },
  61: { row: 8, col: 7 },
  62: { row: 8, col: 8 },
  63: { row: 8, col: 9 },
  64: { row: 8, col: 10 },
  65: { row: 8, col: 11 },
  66: { row: 8, col: 12 },
  67: { row: 8, col: 13 },
  68: { row: 8, col: 14 },
  69: { row: 8, col: 15 },
  70: { row: 8, col: 16 },
  71: { row: 8, col: 17 },

  // Actinides (Row 9, f-block)
  90: { row: 9, col: 4 },
  91: { row: 9, col: 5 },
  92: { row: 9, col: 6 },
  93: { row: 9, col: 7 },
  94: { row: 9, col: 8 },
  95: { row: 9, col: 9 },
  96: { row: 9, col: 10 },
  97: { row: 9, col: 11 },
  98: { row: 9, col: 12 },
  99: { row: 9, col: 13 },
  100: { row: 9, col: 14 },
  101: { row: 9, col: 15 },
  102: { row: 9, col: 16 },
  103: { row: 9, col: 17 }
};

// Export the data for use in other modules
export { elements, elementPositions };
