// Periodic Table Element Data
const elements = [
  {
    atomicNumber: 1,
    symbol: "H",
    name: "Hydrogen",
    atomicWeight: 1.008,
    category: "nonmetal",
    electronConfiguration: "1s¹",
    electronegativity: 2.2,
    density: 0.0000899,
    meltingPoint: -259.14,
    boilingPoint: -252.87,
    discoveryYear: 1766,
    description: "Hydrogen is the lightest element and the most abundant chemical substance in the universe, constituting roughly 75% of all normal matter."
  },
  {
    atomicNumber: 2,
    symbol: "He",
    name: "Helium",
    atomicWeight: 4.0026,
    category: "noble-gas",
    electronConfiguration: "1s²",
    electronegativity: null,
    density: 0.0001785,
    meltingPoint: -272.2,
    boilingPoint: -268.93,
    discoveryYear: 1868,
    description: "Helium is a colorless, odorless, tasteless, non-toxic, inert, monatomic gas, the first in the noble gas group in the periodic table."
  },
  {
    atomicNumber: 3,
    symbol: "Li",
    name: "Lithium",
    atomicWeight: 6.94,
    category: "alkali-metal",
    electronConfiguration: "1s² 2s¹",
    electronegativity: 0.98,
    density: 0.534,
    meltingPoint: 180.54,
    boilingPoint: 1342,
    discoveryYear: 1817,
    description: "Lithium is a soft, silvery-white alkali metal. Under standard conditions, it is the lightest metal and the lightest solid element."
  },
  {
    atomicNumber: 4,
    symbol: "Be",
    name: "Beryllium",
    atomicWeight: 9.0122,
    category: "alkaline-earth-metal",
    electronConfiguration: "1s² 2s²",
    electronegativity: 1.57,
    density: 1.85,
    meltingPoint: 1287,
    boilingPoint: 2470,
    discoveryYear: 1797,
    description: "Beryllium is a relatively rare element in the universe. It is a divalent element which occurs naturally only in combination with other elements in minerals."
  },
  {
    atomicNumber: 5,
    symbol: "B",
    name: "Boron",
    atomicWeight: 10.81,
    category: "metalloid",
    electronConfiguration: "1s² 2s² 2p¹",
    electronegativity: 2.04,
    density: 2.34,
    meltingPoint: 2076,
    boilingPoint: 3927,
    discoveryYear: 1808,
    description: "Boron is a chemical element with symbol B and atomic number 5. Produced entirely by cosmic ray spallation and supernovae and not by stellar nucleosynthesis, it is a low-abundance element in the Solar system and in the Earth's crust."
  },
  {
    atomicNumber: 6,
    symbol: "C",
    name: "Carbon",
    atomicWeight: 12.011,
    category: "nonmetal",
    electronConfiguration: "1s² 2s² 2p²",
    electronegativity: 2.55,
    density: 2.267,
    meltingPoint: 3550,
    boilingPoint: 4027,
    discoveryYear: "Ancient",
    description: "Carbon is a chemical element with symbol C and atomic number 6. It is nonmetallic and tetravalent—making four electrons available to form covalent chemical bonds. It belongs to group 14 of the periodic table."
  },
  {
    atomicNumber: 7,
    symbol: "N",
    name: "Nitrogen",
    atomicWeight: 14.007,
    category: "nonmetal",
    electronConfiguration: "1s² 2s² 2p³",
    electronegativity: 3.04,
    density: 0.0012506,
    meltingPoint: -210.1,
    boilingPoint: -195.79,
    discoveryYear: 1772,
    description: "Nitrogen is a chemical element with symbol N and atomic number 7. It was first discovered and isolated by Scottish physician Daniel Rutherford in 1772."
  },
  {
    atomicNumber: 8,
    symbol: "O",
    name: "Oxygen",
    atomicWeight: 15.999,
    category: "nonmetal",
    electronConfiguration: "1s² 2s² 2p⁴",
    electronegativity: 3.44,
    density: 0.001429,
    meltingPoint: -218.79,
    boilingPoint: -182.95,
    discoveryYear: 1774,
    description: "Oxygen is a chemical element with symbol O and atomic number 8. It is a member of the chalcogen group on the periodic table, a highly reactive nonmetal, and an oxidizing agent that readily forms oxides with most elements as well as with other compounds."
  },
  {
    atomicNumber: 9,
    symbol: "F",
    name: "Fluorine",
    atomicWeight: 18.998,
    category: "nonmetal",
    electronConfiguration: "1s² 2s² 2p⁵",
    electronegativity: 3.98,
    density: 0.001696,
    meltingPoint: -219.67,
    boilingPoint: -188.11,
    discoveryYear: 1886,
    description: "Fluorine is a chemical element with symbol F and atomic number 9. It is the lightest halogen and exists as a highly toxic pale yellow diatomic gas at standard conditions."
  },
  {
    atomicNumber: 10,
    symbol: "Ne",
    name: "Neon",
    atomicWeight: 20.180,
    category: "noble-gas",
    electronConfiguration: "1s² 2s² 2p⁶",
    electronegativity: null,
    density: 0.0008999,
    meltingPoint: -248.59,
    boilingPoint: -246.08,
    discoveryYear: 1898,
    description: "Neon is a chemical element with symbol Ne and atomic number 10. It is a noble gas. Neon is a colorless, odorless, inert monatomic gas under standard conditions, with about two-thirds the density of air."
  },
  // First 10 elements shown, more would be added similarly
  // We'll add some key elements across the periodic table
  {
    atomicNumber: 11,
    symbol: "Na",
    name: "Sodium",
    atomicWeight: 22.990,
    category: "alkali-metal",
    electronConfiguration: "1s² 2s² 2p⁶ 3s¹",
    electronegativity: 0.93,
    density: 0.97,
    meltingPoint: 97.72,
    boilingPoint: 883,
    discoveryYear: 1807,
    description: "Sodium is a chemical element with symbol Na and atomic number 11. It is a soft, silvery-white, highly reactive metal."
  },
  {
    atomicNumber: 12,
    symbol: "Mg",
    name: "Magnesium",
    atomicWeight: 24.305,
    category: "alkaline-earth-metal",
    electronConfiguration: "1s² 2s² 2p⁶ 3s²",
    electronegativity: 1.31,
    density: 1.74,
    meltingPoint: 650,
    boilingPoint: 1090,
    discoveryYear: 1808,
    description: "Magnesium is a chemical element with symbol Mg and atomic number 12. It is a shiny gray solid which bears a close physical resemblance to the other five elements in the second column of the periodic table."
  },
  {
    atomicNumber: 13,
    symbol: "Al",
    name: "Aluminum",
    atomicWeight: 26.982,
    category: "post-transition-metal",
    electronConfiguration: "1s² 2s² 2p⁶ 3s² 3p¹",
    electronegativity: 1.61,
    density: 2.7,
    meltingPoint: 660.32,
    boilingPoint: 2519,
    discoveryYear: 1825,
    description: "Aluminum is a chemical element with symbol Al and atomic number 13. It is a silvery-white, soft, nonmagnetic, ductile metal in the boron group."
  },
  {
    atomicNumber: 18,
    symbol: "Ar",
    name: "Argon",
    atomicWeight: 39.948,
    category: "noble-gas",
    electronConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶",
    electronegativity: null,
    density: 0.0017837,
    meltingPoint: -189.35,
    boilingPoint: -185.85,
    discoveryYear: 1894,
    description: "Argon is a chemical element with symbol Ar and atomic number 18. It is in group 18 of the periodic table and is a noble gas."
  },
  {
    atomicNumber: 19,
    symbol: "K",
    name: "Potassium",
    atomicWeight: 39.098,
    category: "alkali-metal",
    electronConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s¹",
    electronegativity: 0.82,
    density: 0.89,
    meltingPoint: 63.38,
    boilingPoint: 759,
    discoveryYear: 1807,
    description: "Potassium is a chemical element with symbol K and atomic number 19. It was first isolated from potash, the ashes of plants, from which its name derives."
  },
  {
    atomicNumber: 20,
    symbol: "Ca",
    name: "Calcium",
    atomicWeight: 40.078,
    category: "alkaline-earth-metal",
    electronConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s²",
    electronegativity: 1.00,
    density: 1.55,
    meltingPoint: 842,
    boilingPoint: 1484,
    discoveryYear: 1808,
    description: "Calcium is a chemical element with symbol Ca and atomic number 20. As an alkaline earth metal, calcium is a reactive metal that forms a dark oxide-nitride layer when exposed to air."
  },
  {
    atomicNumber: 26,
    symbol: "Fe",
    name: "Iron",
    atomicWeight: 55.845,
    category: "transition-metal",
    electronConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d⁶",
    electronegativity: 1.83,
    density: 7.87,
    meltingPoint: 1538,
    boilingPoint: 2862,
    discoveryYear: "Ancient",
    description: "Iron is a chemical element with symbol Fe and atomic number 26. It is a metal in the first transition series. It is by mass the most common element on Earth, forming much of Earth's outer and inner core."
  },
  {
    atomicNumber: 29,
    symbol: "Cu",
    name: "Copper",
    atomicWeight: 63.546,
    category: "transition-metal",
    electronConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s¹ 3d¹⁰",
    electronegativity: 1.90,
    density: 8.96,
    meltingPoint: 1084.62,
    boilingPoint: 2562,
    discoveryYear: "Ancient",
    description: "Copper is a chemical element with symbol Cu and atomic number 29. It is a soft, malleable, and ductile metal with very high thermal and electrical conductivity."
  },
  {
    atomicNumber: 36,
    symbol: "Kr",
    name: "Krypton",
    atomicWeight: 83.80,
    category: "noble-gas",
    electronConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶",
    electronegativity: 3.00,
    density: 0.003733,
    meltingPoint: -157.36,
    boilingPoint: -153.22,
    discoveryYear: 1898,
    description: "Krypton is a chemical element with symbol Kr and atomic number 36. It is a member of group 18 (noble gases) elements. A colorless, odorless, tasteless noble gas, krypton occurs in trace amounts in the atmosphere and is often used with other rare gases in fluorescent lamps."
  },
  {
    atomicNumber: 47,
    symbol: "Ag",
    name: "Silver",
    atomicWeight: 107.87,
    category: "transition-metal",
    electronConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s¹ 4d¹⁰",
    electronegativity: 1.93,
    density: 10.49,
    meltingPoint: 961.78,
    boilingPoint: 2162,
    discoveryYear: "Ancient",
    description: "Silver is a chemical element with symbol Ag and atomic number 47. A soft, white, lustrous transition metal, it exhibits the highest electrical conductivity, thermal conductivity, and reflectivity of any metal."
  },
  {
    atomicNumber: 50,
    symbol: "Sn",
    name: "Tin",
    atomicWeight: 118.71,
    category: "post-transition-metal",
    electronConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p²",
    electronegativity: 1.96,
    density: 7.31,
    meltingPoint: 231.93,
    boilingPoint: 2602,
    discoveryYear: "Ancient",
    description: "Tin is a chemical element with symbol Sn and atomic number 50. It is a post-transition metal in group 14 of the periodic table. It is obtained chiefly from the mineral cassiterite, which contains tin dioxide, SnO₂."
  },
  {
    atomicNumber: 53,
    symbol: "I",
    name: "Iodine",
    atomicWeight: 126.90,
    category: "nonmetal",
    electronConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁵",
    electronegativity: 2.66,
    density: 4.93,
    meltingPoint: 113.7,
    boilingPoint: 184.3,
    discoveryYear: 1811,
    description: "Iodine is a chemical element with symbol I and atomic number 53. The name is from Greek ἰοειδής ioeidēs, meaning violet or purple, due to the color of elemental iodine vapor."
  },
  {
    atomicNumber: 54,
    symbol: "Xe",
    name: "Xenon",
    atomicWeight: 131.29,
    category: "noble-gas",
    electronConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶",
    electronegativity: 2.60,
    density: 0.005887,
    meltingPoint: -111.75,
    boilingPoint: -108.12,
    discoveryYear: 1898,
    description: "Xenon is a chemical element with symbol Xe and atomic number 54. It is a colorless, dense, odorless noble gas found in the Earth's atmosphere in trace amounts."
  },
  {
    atomicNumber: 79,
    symbol: "Au",
    name: "Gold",
    atomicWeight: 196.97,
    category: "transition-metal",
    electronConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s¹ 4f¹⁴ 5d¹⁰",
    electronegativity: 2.54,
    density: 19.3,
    meltingPoint: 1064.18,
    boilingPoint: 2856,
    discoveryYear: "Ancient",
    description: "Gold is a chemical element with symbol Au and atomic number 79, making it one of the higher atomic number elements that occur naturally. In its purest form, it is a bright, slightly reddish yellow, dense, soft, malleable, and ductile metal."
  },
  {
    atomicNumber: 80,
    symbol: "Hg",
    name: "Mercury",
    atomicWeight: 200.59,
    category: "transition-metal",
    electronConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f¹⁴ 5d¹⁰",
    electronegativity: 2.00,
    density: 13.59,
    meltingPoint: -38.83,
    boilingPoint: 356.73,
    discoveryYear: "Ancient",
    description: "Mercury is a chemical element with symbol Hg and atomic number 80. It is commonly known as quicksilver and was formerly named hydrargyrum. A heavy, silvery d-block element, mercury is the only metallic element that is liquid at standard conditions for temperature and pressure."
  },
  {
    atomicNumber: 82,
    symbol: "Pb",
    name: "Lead",
    atomicWeight: 207.2,
    category: "post-transition-metal",
    electronConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f¹⁴ 5d¹⁰ 6p²",
    electronegativity: 2.33,
    density: 11.34,
    meltingPoint: 327.46,
    boilingPoint: 1749,
    discoveryYear: "Ancient",
    description: "Lead is a chemical element with symbol Pb and atomic number 82. It is a heavy metal that is denser than most common materials. Lead is soft and malleable, and also has a relatively low melting point."
  },
  {
    atomicNumber: 92,
    symbol: "U",
    name: "Uranium",
    atomicWeight: 238.03,
    category: "actinide",
    electronConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d¹⁰ 4p⁶ 5s² 4d¹⁰ 5p⁶ 6s² 4f¹⁴ 5d¹⁰ 6p⁶ 7s² 5f³ 6d¹",
    electronegativity: 1.38,
    density: 19.1,
    meltingPoint: 1132.2,
    boilingPoint: 4131,
    discoveryYear: 1789,
    description: "Uranium is a chemical element with symbol U and atomic number 92. It is a silvery-white metal in the actinide series of the periodic table. A uranium atom has 92 protons and 92 electrons, of which 6 are valence electrons."
  }
  // Note: This is a subset of elements for demonstration
  // A complete implementation would include all 118 elements
];

// Generate layout positions for elements in the periodic table
const elementPositions = {
  // Row 1
  1: { row: 1, col: 1 },
  2: { row: 1, col: 18 },
  
  // Row 2
  3: { row: 2, col: 1 },
  4: { row: 2, col: 2 },
  5: { row: 2, col: 13 },
  6: { row: 2, col: 14 },
  7: { row: 2, col: 15 },
  8: { row: 2, col: 16 },
  9: { row: 2, col: 17 },
  10: { row: 2, col: 18 },
  
  // Row 3
  11: { row: 3, col: 1 },
  12: { row: 3, col: 2 },
  13: { row: 3, col: 13 },
  14: { row: 3, col: 14 },
  15: { row: 3, col: 15 },
  16: { row: 3, col: 16 },
  17: { row: 3, col: 17 },
  18: { row: 3, col: 18 },
  
  // Row 4
  19: { row: 4, col: 1 },
  20: { row: 4, col: 2 },
  21: { row: 4, col: 3 },
  22: { row: 4, col: 4 },
  23: { row: 4, col: 5 },
  24: { row: 4, col: 6 },
  25: { row: 4, col: 7 },
  26: { row: 4, col: 8 },
  27: { row: 4, col: 9 },
  28: { row: 4, col: 10 },
  29: { row: 4, col: 11 },
  30: { row: 4, col: 12 },
  31: { row: 4, col: 13 },
  32: { row: 4, col: 14 },
  33: { row: 4, col: 15 },
  34: { row: 4, col: 16 },
  35: { row: 4, col: 17 },
  36: { row: 4, col: 18 },
  
  // Row 5
  37: { row: 5, col: 1 },
  38: { row: 5, col: 2 },
  39: { row: 5, col: 3 },
  40: { row: 5, col: 4 },
  41: { row: 5, col: 5 },
  42: { row: 5, col: 6 },
  43: { row: 5, col: 7 },
  44: { row: 5, col: 8 },
  45: { row: 5, col: 9 },
  46: { row: 5, col: 10 },
  47: { row: 5, col: 11 },
  48: { row: 5, col: 12 },
  49: { row: 5, col: 13 },
  50: { row: 5, col: 14 },
  51: { row: 5, col: 15 },
  52: { row: 5, col: 16 },
  53: { row: 5, col: 17 },
  54: { row: 5, col: 18 },
  
  // Row 6
  55: { row: 6, col: 1 },
  56: { row: 6, col: 2 },
  57: { row: 6, col: 3 },
  72: { row: 6, col: 4 },
  73: { row: 6, col: 5 },
  74: { row: 6, col: 6 },
  75: { row: 6, col: 7 },
  76: { row: 6, col: 8 },
  77: { row: 6, col: 9 },
  78: { row: 6, col: 10 },
  79: { row: 6, col: 11 },
  80: { row: 6, col: 12 },
  81: { row: 6, col: 13 },
  82: { row: 6, col: 14 },
  83: { row: 6, col: 15 },
  84: { row: 6, col: 16 },
  85: { row: 6, col: 17 },
  86: { row: 6, col: 18 },
  
  // Row 7
  87: { row: 7, col: 1 },
  88: { row: 7, col: 2 },
  89: { row: 7, col: 3 },
  104: { row: 7, col: 4 },
  105: { row: 7, col: 5 },
  106: { row: 7, col: 6 },
  107: { row: 7, col: 7 },
  108: { row: 7, col: 8 },
  109: { row: 7, col: 9 },
  110: { row: 7, col: 10 },
  111: { row: 7, col: 11 },
  112: { row: 7, col: 12 },
  113: { row: 7, col: 13 },
  114: { row: 7, col: 14 },
  115: { row: 7, col: 15 },
  116: { row: 7, col: 16 },
  117: { row: 7, col: 17 },
  118: { row: 7, col: 18 },
  
  // Lanthanides (Row 8)
  58: { row: 8, col: 4 },
  59: { row: 8, col: 5 },
  60: { row: 8, col: 6 },
  61: { row: 8, col: 7 },
  62: { row: 8, col: 8 },
  63: { row: 8, col: 9 },
  64: { row: 8, col: 10 },
  65: { row: 8, col: 11 },
  66: { row: 8, col: 12 },
  67: { row: 8, col: 13 },
  68: { row: 8, col: 14 },
  69: { row: 8, col: 15 },
  70: { row: 8, col: 16 },
  71: { row: 8, col: 17 },
  
  // Actinides (Row 9)
  90: { row: 9, col: 4 },
  91: { row: 9, col: 5 },
  92: { row: 9, col: 6 },
  93: { row: 9, col: 7 },
  94: { row: 9, col: 8 },
  95: { row: 9, col: 9 },
  96: { row: 9, col: 10 },
  97: { row: 9, col: 11 },
  98: { row: 9, col: 12 },
  99: { row: 9, col: 13 },
  100: { row: 9, col: 14 },
  101: { row: 9, col: 15 },
  102: { row: 9, col: 16 },
  103: { row: 9, col: 17 }
};

// Export the data for use in other modules
export { elements, elementPositions };